services:
  - type: web
    name: medi-back
    runtime: docker
    plan: starter
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
